apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume1
  namespace: poc-6666
  labels:
    type: local1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: "/root/poc-6666/proj1/data1"
---
